/// Flutter icons TicTacToe
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TicTacToe
///      fonts:
///       - asset: fonts/TicTacToe.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class TicTacToeIcons {
  TicTacToeIcons._();

  static const _kFontFam = 'TicTacToe';

  static const IconData cancel = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData circle_empty = IconData(0xf10c, fontFamily: _kFontFam);
}
